/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.h7g5.model.impl;

import com.liferay.h7g5.model.H7G5Entry;
import com.liferay.h7g5.service.H7G5EntryLocalServiceUtil;

/**
 * The extended model base implementation for the H7G5Entry service. Represents a row in the &quot;OHQIWTSFHL_H7G5Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link H7G5EntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see H7G5EntryImpl
 * @see H7G5Entry
 * @generated
 */
public abstract class H7G5EntryBaseImpl
	extends H7G5EntryModelImpl implements H7G5Entry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a h7g5 entry model instance should use the <code>H7G5Entry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			H7G5EntryLocalServiceUtil.addH7G5Entry(this);
		}
		else {
			H7G5EntryLocalServiceUtil.updateH7G5Entry(this);
		}
	}

}